imag0: continuumio/miniconda3:latest

pipelines:
  branches:
    master:
        - step:
            caches:
              - pip
              - conda
            script: # Build env and run tests
              - apt-get update && apt-get -y install build-essential
              - conda env update -n diyenv --file  env.yml
              - source activate diyenv
              - python setup.py develop
              
              # Running tests
              - pytest --junitxml=junit/test-results.xml --cov=hydrodiy --cov-config=.coveragerc --cov-report=xml hydrodiy

              # Pylint
              #pylint --rcfile pylintrc hydrodiy > pylint_results

              # Install hydrodiy
              - python setup.py install
                
              # Running examples
              - python -W ignore examples/run_all_examples.py

              # Get list of functions skipping files with basemap
              - python -W ignore listmembers.py -s

              # Remove C modules and rerun tests
              - rm -f *.so
              - rm -rf build
              - pytest --junitxml=junit/test-results.xml --cov=hydrodiy --cov-config=.coveragerc --cov-report=xml hydrodiy

            artifacts: 
              - cov_html_gridverif/**

definitions:
  caches:
    conda:  ~/.conda/envs/diyenv

