name: Build hydrodiy

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 5
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name : Install hydrodiy package 
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        run: |
          set -e
          uv run ruff check src/hydrodiy/data/*.py
          uv run ruff check src/hydrodiy/gis/*.py
          uv run ruff check src/hydrodiy/stat/*.py
          uv run ruff check src/hydrodiy/plot/*.py

      - name: Run tests
        run: |
          uv run --locked pytest --cov=hydrodiy --cov-report=xml --cov-report=html --cov-report=term-missing src/hydrodiy
      
      - name: Parse coverage report and create badge
        run: |
          uv run --locked python -c "import xml.etree.ElementTree as ET; from anybadge import Badge; cov = float(ET.parse('coverage.xml').getroot().get('line-rate')) * 100; covbadge = Badge('Coverage', value=f'{cov:0.0f}%', thresholds={60:'red', 70:'orange', 80:'lightgreen', 90:'green'}); covbadge.write_badge('coverage_badge.svg', True)"

      - name: Update gist badge
        run: |
          sed 's/\"/\\\"/g' coverage_badge.svg > coverage_badge.txt
          echo "{\"files\": {\"coverage_badge.svg\": {\"content\": \"$(cat coverage_badge.txt)\"}}}" > coverage_badge.json
          curl -X PATCH -H "Authorization: token ${{ secrets.COVERAGE_GIST_TOKEN }}" \
                -d @coverage_badge.json \
                "https://api.github.com/gists/${{ secrets.COVERAGE_GIST_ID }}"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-coverage
          path: htmlcov/*.* 

      - name: Run examples
        run: |
          uv run --locked python examples/run_all_examples.py
        
